name: complex workflow


on: push

jobs:

  job1:

    name: first job 
    runs-on: ubuntu-latest
    
    steps:
      - name: data de jour 
      - run: date



  job2:

    name: second job
    runs-on: ubuntu-latest

    steps:
      - name: date du jour
      - run: date

    runs-on: ubuntu-latest
    steps:
      - name: date du jour
      - run: date 


  job3:
    name: third job
    runs-on: ubuntu-latest

    steps:
      - name: date du jour  
      - run: date


 job4:
    needs: [job1, job2]
    name: last job 
    runs-on: ubuntu-latest
    
    steps:
      - name: date du jour
      - run: date

   






















