name: Workflow  with conditions on the branch
on:
  push:
    branches:
             - dev 
  
jobs:
  job1:
    name: first job 
    runs-on: ubuntu-latest
    steps:
          name: showing the date with a command
          run: date 


    
